name: Deploy blockchain content to app.degenvets.com

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages-app"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Prepare deployment
        run: |
          mkdir -p ./output-app
          cp -R ./GX-blockchain/* ./output-app/
          cp ./GX-blockchain/static/index.html ./output-app/index.html
          echo "app.degenvets.com" > ./output-app/CNAME

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages-app
          path: ./output-app
